"""ClipFusion — 10 Arquétipos Emocionais para identificação de cortes virais."""

ARCHETYPES = {
    "01_despertar": {
        "id": "01_despertar", "nome": "O Despertar", "emoji": "⚡",
        "emocao": "Curiosidade + Urgência",
        "descricao": "Algo que muda a percepção — o espectador descobre que estava errado sobre algo importante.",
        "hook_template": ["Você sabia que {tema}? Quase ninguém sabe.",
                          "{tema} — o que ninguém te contou."],
        "gatilho": "novidade + quebra de crença", "cta": "Salva pra ver depois",
        "cores": ["#FFD700", "#000000"], "musica": "Ambient crescente", "duracao_ideal": "15–30s",
    },
    "02_tensao": {
        "id": "02_tensao", "nome": "A Tensão", "emoji": "⏰",
        "emocao": "Medo + Antecipação",
        "descricao": "Risco iminente, prazo, ameaça — o espectador sente urgência.",
        "hook_template": ["Em {tempo} você vai {consequencia} se continuar assim.",
                          "Cuidado: {tema} pode estar destruindo {algo}."],
        "gatilho": "medo de perda + urgência", "cta": "Comenta se você faz isso",
        "cores": ["#FF0000", "#1a1a1a"], "musica": "Suspense percussivo", "duracao_ideal": "20–45s",
    },
    "03_confronto": {
        "id": "03_confronto", "nome": "O Confronto", "emoji": "🔥",
        "emocao": "Raiva + Determinação",
        "descricao": "Enfrentamento direto — opinião forte, posição clara, contra-narrativa.",
        "hook_template": ["Chega de {estado_negativo}. Isso precisa parar.",
                          "Todo mundo está errado sobre {tema}."],
        "gatilho": "controvérsia + identidade", "cta": "Concorda ou discorda? Comenta",
        "cores": ["#8B0000", "#000000"], "musica": "Rock/eletrônico", "duracao_ideal": "20–40s",
    },
    "04_virada": {
        "id": "04_virada", "nome": "A Virada", "emoji": "✨",
        "emocao": "Esperança + Empoderamento",
        "descricao": "Mudança de perspectiva — existe um caminho melhor que poucos conhecem.",
        "hook_template": ["Como {publico} transformou {problema} em {resultado}.",
                          "O que mudou tudo na minha vida sobre {tema}."],
        "gatilho": "transformação + esperança", "cta": "Compartilha com quem precisa",
        "cores": ["#00AA44", "#000000"], "musica": "Motivacional crescente", "duracao_ideal": "30–60s",
    },
    "05_revelacao": {
        "id": "05_revelacao", "nome": "A Revelação", "emoji": "🤯",
        "emocao": "Surpresa + Fascínio",
        "descricao": "Segredo revelado, dado inesperado — informação que poucos têm.",
        "hook_template": ["O segredo que {industria} não quer que você saiba.",
                          "Descobriram que {tema} — ninguém está falando sobre isso."],
        "gatilho": "curiosidade + exclusividade", "cta": "Marca alguém que precisa saber",
        "cores": ["#6B00CC", "#000000"], "musica": "Misterioso + build-up", "duracao_ideal": "20–45s",
    },
    "06_justo_engolido": {
        "id": "06_justo_engolido", "nome": "O Justo Engolido", "emoji": "💢",
        "emocao": "Injustiça + Revolta",
        "descricao": "Alguém sendo prejudicado — o espectador quer justiça.",
        "hook_template": ["Por que {publico} está sendo enganado sobre {tema}?",
                          "{publico} trabalha {esforco} e ainda {injustica}."],
        "gatilho": "revolta + identificação", "cta": "Compartilha para mais pessoas saberem",
        "cores": ["#FF6600", "#000000"], "musica": "Dramática + intensa", "duracao_ideal": "25–50s",
    },
    "07_transformacao": {
        "id": "07_transformacao", "nome": "A Transformação", "emoji": "🦋",
        "emocao": "Superação + Inspiração",
        "descricao": "Jornada antes/depois — prova social de que a mudança é possível.",
        "hook_template": ["Antes e depois: como {publico} superou {problema}.",
                          "{tempo} atrás eu era {estado_negativo}. Hoje sou {estado_positivo}."],
        "gatilho": "inspiração + prova social", "cta": "Comenta sua história",
        "cores": ["#00CED1", "#FFFFFF"], "musica": "Emocional + crescente", "duracao_ideal": "45–90s",
    },
    "08_resolucao": {
        "id": "08_resolucao", "nome": "A Resolução", "emoji": "✅",
        "emocao": "Alívio + Satisfação",
        "descricao": "Solução entregue, problema resolvido — valor prático imediato.",
        "hook_template": ["A solução definitiva para {problema} — em {tempo}.",
                          "Pare de sofrer com {problema}. Faz isso:"],
        "gatilho": "utilidade + alívio", "cta": "Salva esse vídeo",
        "cores": ["#32CD32", "#000000"], "musica": "Calma + satisfatória", "duracao_ideal": "30–60s",
    },
    "09_impacto": {
        "id": "09_impacto", "nome": "O Impacto", "emoji": "💥",
        "emocao": "Choque + Admiração",
        "descricao": "Número forte, resultado surpreendente, escala inesperada.",
        "hook_template": ["{numero} pessoas {resultado} com {tema}. Isso é real.",
                          "O impacto real de {tema} em números."],
        "gatilho": "escala + credibilidade", "cta": "Comenta se acreditou nisso",
        "cores": ["#FF1493", "#000000"], "musica": "Eletrônica impactante", "duracao_ideal": "15–30s",
    },
    "10_encerramento": {
        "id": "10_encerramento", "nome": "O Encerramento", "emoji": "🎯",
        "emocao": "Realização + Fechamento",
        "descricao": "Lição aprendida, conclusão poderosa — o espectador sai com algo.",
        "hook_template": ["A lição mais importante que aprendi sobre {tema}.",
                          "Se eu pudesse voltar atrás sobre {tema}, faria isso diferente."],
        "gatilho": "sabedoria + reflexão", "cta": "Salva e volta pra ler quando precisar",
        "cores": ["#C0C0C0", "#000000"], "musica": "Orquestral suave", "duracao_ideal": "20–40s",
    },
}
